# harmonianet-backend/fly.toml

app = "harmonia-net"  # Can change after initial deploy

[env]
PORT = "8080"

[build]
  builder = "docker"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
